version: '3.8'

services:
  # MongoDB database
  mongodb:
    image: mongo:7.0
    container_name: email-app-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: email-management
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - email-app-network

  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: email-app-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/email-management?authSource=admin
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key-change-this-in-production}
      CLAUDE_API_KEY: ${CLAUDE_API_KEY}
      CLAUDE_API_URL: https://api.anthropic.com/v1/messages
      AWS_REGION: ${AWS_REGION:-us-east-1}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      SES_FROM_EMAIL: ${SES_FROM_EMAIL}
      CLIENT_URL: ${CLIENT_URL:-http://localhost:3000}
    depends_on:
      - mongodb
    networks:
      - email-app-network
    volumes:
      - ./logs:/app/logs

  # Frontend React App
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: email-app-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - email-app-network

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: email-app-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - email-app-network

volumes:
  mongodb_data:
    driver: local

networks:
  email-app-network:
    driver: bridge